//$
//(selector)
//.accion
$(function(){
    $('.container').mouseenter(function(){
        $("#stock").slideDown();
    })
    $('.container').mouseleave(function(){
        $("#stock").slideUp();
    })
});
//------------------
